---
- name: NAPALM data structure conversion
  hosts: cisco1
  tasks:
    - name: Gather NAPALM facts
      vars:
        ansible_connection: local
      napalm.napalm.get_facts: 
        filter: "arp_table"

    - ansible.builtin.debug:
        var: napalm_arp_table

    - name: Extract ip and mac fields into lists
      ansible.builtin.set_fact:
        ip_addr: "{{ napalm_arp_table | map(attribute='ip') | list }}"
        mac: "{{ napalm_arp_table | map(attribute='mac') | list }}"

    - ansible.builtin.debug:
        var: mac

    - name: Create list of lists using zip
      ansible.builtin.set_fact:
        ip_dict: "{{ ip_addr | zip(mac) | list }}"

    - ansible.builtin.debug:
        var: ip_dict

    - name: Create dict from list of lists
      ansible.builtin.debug:
        msg: "{{ dict(ip_dict) }}"
