---
- name: Test putting a file onto Cisco IOS/IOS-XE device
  hosts: cisco1
  # ansible-pylibssh errors out here (force paramiko usage)
  vars:
    ansible_network_cli_ssh_type: paramiko
  tasks:
    - name: Copy file
      ansible.netcommon.net_put:
        src: my_file1.txt
        dest : flash:/my_file1.txt
        protocol: scp
