---
- name: Test napalm merge
  hosts: arista5
  gather_facts: False
  tasks:

    - name: Generate VLAN configuration
      ansible.builtin.template:
        src: "templates/{{ ansible_network_os }}/vlans.j2"
        dest: "ASSEMBLE/{{ ansible_network_os }}/10-vlan.cfg"
      tags: build

    - name: Generate interface configuration
      ansible.builtin.template:
        src: "templates/{{ ansible_network_os }}/interfaces.j2"
        dest: "ASSEMBLE/{{ ansible_network_os }}/20-interfaces.cfg"
      tags: build

    - name: Assemble the configuration
      ansible.builtin.assemble:
        src: "ASSEMBLE/{{ ansible_network_os }}/"
        dest: "CFGS/{{ ansible_network_os }}.cfg"
      tags: build

    - name: "Deploy configuration to the device (merge)"
      napalm.napalm.install_config:
        replace_config: False
        commit_changes: False
        config_file: "CFGS/{{ ansible_network_os }}.cfg"
        diff_file: "DIFFS/{{ inventory_hostname }}.txt"
      tags: deploy
