---
- name: Pipe JSON
  hosts: arista5
  gather_facts: False
  tasks:
    - name: Executing command
      arista.eos.eos_command:
        commands: show version | json
      register: output

    - ansible.builtin.set_fact:
        show_ver: "{{ output['stdout'][0] }}"

    - ansible.builtin.debug:
        msg: "{{ show_ver }}"
        #msg: "OS Version: {{ show_ver.version }}"
