---
- name: Pipe JSON NX-OS
  hosts: nxos1
  gather_facts: False
  tasks:
    - name: Executing command
      cisco.nxos.nxos_command:
        commands: show version | json
      register: output

    - ansible.builtin.set_fact:
        show_ver: "{{ output['stdout'][0] }}"

    - ansible.builtin.debug:
        msg: "Platform: {{ show_ver.chassis_id }}"
