---
- name: Bonus1, exercise5
  hosts: arista5
  gather_facts: False
  tasks:
    - name: Generate full configurations from a template
      ansible.builtin.template:
        src: "templates/{{ inventory_hostname }}.j2"
        dest: "CFGS/{{ inventory_hostname }}-load.txt"
      tags: build

    - name: Use NAPALM to perform full configuration replace
      napalm.napalm.install_config:
        replace_config: True
        commit_changes: False
        config_file: "CFGS/{{ inventory_hostname }}-load.txt"
        diff_file: "DIFFS/{{ inventory_hostname }}.txt"
      tags: deploy
