- name: Exercise 3b
  hosts: arista
  gather_facts: True

  vars:
    platform: "arista_eos"
    command: "show vlan"
    textfsm_rel_path: "ntc-templates/ntc_templates/templates/"

  tasks:
    - name: Executing command
      arista.eos.eos_command:
        commands: "{{ command }}"
      register: output

    - ansible.builtin.debug:
        var: output

    # This is only needed so our automated tests work properly
    - name: "Set home directory as ntc_parse doesn't understand ~"
      ansible.builtin.set_fact:
        textfsm_index: "{{ inventory_dir }}/{{textfsm_rel_path }}"

    - ansible.builtin.set_fact:
        output_parsed: "{{ output.stdout[0] | ntc_parse(command, platform, textfsm_index ) }}"

    - ansible.builtin.debug:
        var: output_parsed
