---
- name: Test napalm merge
  hosts: arista5
  gather_facts: False
  tasks:
    - napalm.napalm.install_config:
        replace_config: False
        commit_changes: False
        diff_file: "DIFFS/{{ inventory_hostname }}.txt"
        config: | 
         interface Loopback98
            ip address 172.31.98.1/24
         interface Loopback99
            ip address 172.31.99.1/24
