---
- name: Generate configuration from a template
  hosts: arista
  gather_facts: False
  tasks:
    - name: Template individual file
      ansible.builtin.template:
        src: "templates/{{ ansible_network_os }}_original/{{ inventory_hostname }}.txt"
        dest: "CFGS/{{ inventory_hostname }}-load.txt"
