---
- name: Retrieve running configuration
  hosts: arista
  gather_facts: False
  tasks:
    - name: get_config
      napalm.napalm.get_facts:
        filter: config

    - name: Save the config locally
      ansible.builtin.copy:
        content: "{{ napalm_config.running }}"
        dest: "{{ inventory_hostname }}.txt"
