---
- name: napalm nxos_ssh
  hosts: nxos1
  gather_facts: False
  tasks:
    - name: Retrieve get_facts, get_interfaces
      napalm.napalm.get_facts:
        filter: facts,interfaces
        dev_os: nxos_ssh

    - ansible.builtin.debug:
        var: napalm_facts
